exclude:
  - node_modules
  - script

sass:
  style: :compressed

theme: jekyll-theme-primer
repository: leandropsouza1/site

github:
  private: false
  license:
    name: MIT
  source:
    branch: "main"
    path: "/"
  repository_url: "https://github.com/leandropsouza1/site"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

title: Leandro Pessoa
description: Local onde utilizo para colocar meus artigos, textos e post que escrevo.
url: https://www.leandropessoa.com.br
git_hub: "https://github.com/leandropsouza1"
linkedin: "https://www.linkedin.com/in/leandropessoa/"
google_analytics: 1234
