exclude:
  - node_modules
  - script

sass:
  style: :compressed

theme: jekyll-theme-primer

github:
  private: false
  license:
    name: MIT
  source:
    branch: "main"
    path: "/"
  repository_url: "https://github.com/leandropsouza1/site"

repository: leandropsouza1/site

github: [metadata]

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

title: Leandro Pessoa
description: Local onde utilizo para colocar meus artigos, textos e post que escrevo.
